### ISSUE TITLE
Problema em classe TestaBanco

### ISSUE THREAD

**Issue by lrsousa** [olaviolacerda/aulas#1]
Na classe TestaBanco esta percorrendo o FOR de 0 até <= a quantidade de contas adicionadas(3).
Ou seja, ele tenta acessar 4 contas quando na verdade só tem 3.

Remova o '='
![capturar](https://cloud.githubusercontent.com/assets/4068511/14400467/eec517b2-fdce-11e5-8a1d-3df460e81775.PNG)

**Comment by olaviolacerda** [comment]
Poxa, valeu mesmo! Abração!

**Comment by olaviolacerda** [comment]
Poxa, valeu mesmo! Abração!
